modLoader="javafml"
loaderVersion="[47,)"
license="All Rights Reserved"
[[mods]]
modId="specialpickaxes"
version="5.10.120"
displayName="Special Pickaxes"
authors="Santi-PdR"
description='''Thirteen tier-IV mining pickaxes with custom abilities, safe scheduled excavation, modded geology support and referenced Terramity textures.'''
[[dependencies.specialpickaxes]]
modId="forge"
mandatory=true
versionRange="[47.3.0,48)"
ordering="NONE"
side="BOTH"
[[dependencies.specialpickaxes]]
modId="minecraft"
mandatory=true
versionRange="[1.20.1,1.20.2)"
ordering="NONE"
side="BOTH"
[[dependencies.specialpickaxes]]
modId="curios"
mandatory=false
versionRange="[5,)"
ordering="AFTER"
side="BOTH"
